name: Mirror Subdirectory from GitLab

on:
  workflow_dispatch:  # Manual trigger via GitHub UI
  schedule:
    - cron: '0 3 * * *'  # Optional: run daily at 3 AM UTC

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone public GitLab repo
        run: |
          git clone https://gitlab.opencode.de/smart-city-potsdam/udp-lorawan/tools.git source-repo
          cd source-repo
          git fetch --unshallow || echo "Already full clone"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install git-filter-repo

      - name: Filter subdirectory (preserve original author)
        run: |
          cd source-repo
          git filter-repo --subdirectory-filter Chirpstack/ChirpTools/

      - name: Push to GitHub target repo
        run: |
          cd source-repo
          git remote add github https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/DerDP/ChirpTools.git
          git push -f github main
